build_from:
  armhf: python:3.11-alpine
  armv7: python:3.11-alpine
  aarch64: python:3.11-alpine
  amd64: python:3.11-alpine
  i386: python:3.11-alpine
args:
  PIP_INDEX_URL: https://pypi.org/simple
